// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAkcdy5W60rCkkyVxf47YGB8Sleysi424',
    appId: '1:30898761140:web:2ea548bf34c9feac4d16e1',
    messagingSenderId: '30898761140',
    projectId: 'ui-color-picker-50342',
    authDomain: 'ui-color-picker-50342.firebaseapp.com',
    storageBucket: 'ui-color-picker-50342.appspot.com',
    measurementId: 'G-1EHE1RJM1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkL1UXhZLyiAcXEo4YHRrp4tskLP6XHDU',
    appId: '1:30898761140:android:545c9e3b801519d64d16e1',
    messagingSenderId: '30898761140',
    projectId: 'ui-color-picker-50342',
    storageBucket: 'ui-color-picker-50342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_sORtNc1jCwtAcx1aRQSpSVqWxt5ZzUs',
    appId: '1:30898761140:ios:da04f8f8e1e9e9bf4d16e1',
    messagingSenderId: '30898761140',
    projectId: 'ui-color-picker-50342',
    storageBucket: 'ui-color-picker-50342.appspot.com',
    iosClientId: '30898761140-2spgedn7hip3tn56ftt3jekrhgb25fhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiColorPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_sORtNc1jCwtAcx1aRQSpSVqWxt5ZzUs',
    appId: '1:30898761140:ios:da04f8f8e1e9e9bf4d16e1',
    messagingSenderId: '30898761140',
    projectId: 'ui-color-picker-50342',
    storageBucket: 'ui-color-picker-50342.appspot.com',
    iosClientId: '30898761140-2spgedn7hip3tn56ftt3jekrhgb25fhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiColorPicker',
  );
}
